"use client";

import Link from "next/link";
import { useState } from "react";
import { ChevronRight } from "lucide-react";
import { PageHeader, PageShell } from "@/components/app/page-shell";
import { PROCESS } from "@/lib/help";
import { SHORTCUTS } from "@/components/app/shortcuts";
import { cn } from "@/lib/utils";

/**
 * The guide (v1.4) — the manual, inside the product.
 *
 * It used to live in docs/MANUAL.md, which is fine for whoever clones the
 * repo and useless to everyone who actually uses Kinolab. Screenshots come
 * from public/help and are regenerated by scripts/capture-help.mjs against
 * the seeded demo, so they can be refreshed without hand-editing anything.
 */

type Section = {
  id: string;
  title: string;
  lede: string;
  body: { text: string; image?: string; caption?: string }[];
};

const SECTIONS: Section[] = [
  {
    id: "visual-workspace",
    title: "Build the visual language",
    lede: "Storyboard, reference board, and character gallery keep the artwork close to the work.",
    body: [
      { text: "Storyboard groups real shot frames in scene order. Search a shot, filter a scene, and open a frame to work on its options. Editors can add scene direction with the pencil. Print board creates a contact sheet you can save as PDF." },
      { text: "Reference board collects production artwork, creative notes, up to six palette colors, and a source or credit URL. Artists can maintain their own cards; editors can maintain the whole board. Archive cards you no longer need, and restore them from Archived." },
      { text: "Characters opens as a gallery of the cast. Concept and Animation link directly to their working phases. Switch to the table for inline prompt editing and final-file links; your choice is remembered on this device." },
    ],
  },
  {
    id: "start",
    title: "Signing in",
    lede: "Kinolab is invite-only. Use the address your producer invited.",
    body: [
      {
        text: "After signing in you land on Productions — everything in your studio, with a bar showing how its shots are spread across statuses. Open one to go in.",
        image: "02-productions.png",
        caption: "Productions",
      },
      {
        text: "Kinolab opens dark. Light lives under Settings › Appearance and is remembered per device. The Review Room stays dark whatever you choose — you cannot judge colour against a bright surround.",
      },
    ],
  },
  {
    id: "my-work",
    title: "Your screen: My work",
    lede: "Every other screen answers how the production is doing. This one answers what is on you.",
    body: [
      {
        text: "Your assigned shots, grouped by whose move it is. Needs you is rework to address or shots with no options yet — and rework comes first, because someone is already waiting on that second pass. With review means your options are in and the decision is someone else's.",
        image: "03-my-work.png",
        caption: "My work",
      },
      {
        text: "Nothing here on your first day is normal. Shots appear the moment a producer puts your name on one.",
      },
    ],
  },
  {
    id: "shot",
    title: "Finding a shot, and adding options",
    lede: "The sheet to find it; the Options tab to work on it.",
    body: [
      {
        text: "Shots opens as a contact sheet — find a shot by looking rather than by reading a code. The coloured edge on each frame is its status, so rework and approved are visible without reading anything. Switch to the table for sorting and bulk edits.",
        image: "06-shots-sheet.png",
        caption: "Shots, as a contact sheet",
      },
      {
        text: "Drop files on the uploader, press ⌘V to paste an image straight in, or browse. Images and video up to 20MB go into Kinolab; bigger files belong in Drive and get attached from there.",
        image: "08-shot-options.png",
        caption: "The Options tab",
      },
      {
        text: "Each upload becomes the next version — v1, v2, v3 — and versions are never renumbered or replaced. A better take is a new version, not an edit of the old one.",
      },
      {
        text: "Fill in the generation details: tool, model, seed and prompt. That is what makes a result repeatable six weeks later, and it is what the provenance export carries out with the film.",
      },
      {
        text: "Shortlist the takes worth comparing. Shortlisting gathers candidates — it decides nothing.",
      },
    ],
  },
  {
    id: "review",
    title: "The Review Room",
    lede: "Where options go side by side and one gets picked.",
    body: [
      {
        text: "Press 1–4 to put that many options on screen. Zoom and pan are shared across every pane, so the same detail stays aligned — which is the whole point when you are checking whether the hands survived.",
        image: "11-review-compare.png",
        caption: "Three options under one shared zoom",
      },
      {
        text: "Bottom left: −, the current zoom, +, and Fit. Scroll zooms toward the cursor, drag pans, 0 returns to Fit. The percentage is relative to fit, not to the image's own pixels — with up to four differently sized images sharing one transform there is no single 100% to show.",
        image: "12-review-zoom.png",
        caption: "Zoomed past the preview",
      },
      {
        text: "Past about 175% you are looking at the cached preview, not the original, and a link appears to open the real file. Do not reject a shot for soft fingers without checking there.",
      },
      {
        text: "S shortlists, X rejects with a reason, P picks. A pick is the decision: one version per shot, recorded with who picked it and why, and copied into the Drive Approved/ folder under its canonical name. Picking another version later supersedes the first, and both stay on the record.",
      },
      {
        text: "Uploaded browser-compatible videos now play directly in the room. Pause the clip and attach its current timestamp to a comment. The timestamp is elapsed time in milliseconds, not SMPTE frame timecode. Click it later to seek to that moment. Resolve finished notes or show resolved notes to reopen them. Drive links still open in Drive; upload an H.264 MP4 review copy for in-app playback.",
      },
    ],
  },
  {
    id: "producers",
    title: "Running the production",
    lede: "The board, the gates and the ledger.",
    body: [
      {
        text: "The Board puts every shot across the six stages. Drag between columns; edit status, assignee and due date on the card. Each stage has a gate: request sign-off, then approve or reject with a note.",
        image: "05-board.png",
        caption: "The Board",
      },
      {
        text: "Decisions is the ledger — every gate, pick and QC sign-off in order, with who and why. Nothing is ever deleted. Export it as CSV, or as a provenance file carrying every prompt, seed, file identity and decision.",
        image: "14-decisions.png",
        caption: "The Decisions ledger",
      },
    ],
  },
];

export default function HelpPage() {
  const [active, setActive] = useState(SECTIONS[0].id);

  return (
    <PageShell>
      <PageHeader
        title="Guide"
        description="How Kinolab works, from a shot being planned to a master shipping."
        favoriteLabel="Guide"
      />

      {/* The process first: it is the shortest thing on the page and the one
          that orients someone who has never seen the tool. */}
      <section className="mb-8 rounded-xl bg-card p-4 ring-1 ring-foreground/10">
        <h2 className="mb-3 text-sm font-semibold">The process, end to end</h2>
        <ol className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
          {PROCESS.map((step) => (
            <li key={step.title} className="rounded-lg bg-muted/40 p-3">
              <p className="font-mono text-[11px] text-tape">{step.title}</p>
              <p className="mt-1 text-sm text-muted-foreground">{step.body}</p>
            </li>
          ))}
        </ol>
      </section>

      <div className="flex flex-col gap-8 lg:flex-row">
        {/* Section nav — sticky, so the walkthrough stays navigable. */}
        <nav className="shrink-0 lg:sticky lg:top-20 lg:h-fit lg:w-44">
          <ul className="flex flex-wrap gap-1 lg:flex-col">
            {SECTIONS.map((section) => (
              <li key={section.id}>
                <a
                  href={`#${section.id}`}
                  onClick={() => setActive(section.id)}
                  className={cn(
                    "flex items-center gap-1 rounded-md px-2.5 py-1.5 text-sm transition-colors",
                    active === section.id
                      ? "bg-accent font-medium text-foreground"
                      : "text-muted-foreground hover:bg-accent/60 hover:text-foreground",
                  )}
                >
                  <ChevronRight className="size-3 shrink-0 opacity-50" />
                  {section.title}
                </a>
              </li>
            ))}
          </ul>
        </nav>

        <div className="min-w-0 flex-1 space-y-12">
          {SECTIONS.map((section) => (
            <section key={section.id} id={section.id} className="scroll-mt-20">
              <h2 className="font-display text-lg font-semibold tracking-tight">
                {section.title}
              </h2>
              <p className="mt-1 text-sm text-muted-foreground">
                {section.lede}
              </p>
              <div className="mt-4 space-y-5">
                {section.body.map((block) => (
                  <div key={block.text}>
                    <p className="text-sm text-foreground/90">{block.text}</p>
                    {block.image && (
                      <figure className="mt-3">
                        {/* eslint-disable-next-line @next/next/no-img-element */}
                        <img
                          src={`/help/${block.image}`}
                          alt={block.caption ?? section.title}
                          loading="lazy"
                          className="w-full rounded-lg ring-1 ring-foreground/10"
                        />
                        {block.caption && (
                          <figcaption className="mt-1.5 font-mono text-[11px] text-muted-foreground">
                            {block.caption}
                          </figcaption>
                        )}
                      </figure>
                    )}
                  </div>
                ))}
              </div>
            </section>
          ))}

          <section id="keys" className="scroll-mt-20">
            <h2 className="font-display text-lg font-semibold tracking-tight">
              Keyboard
            </h2>
            <div className="mt-4 grid gap-6 sm:grid-cols-3">
              {SHORTCUTS.map((group) => (
                <div key={group.title}>
                  <h3 className="mb-2 text-xs font-medium uppercase tracking-wide text-muted-foreground">
                    {group.title}
                  </h3>
                  <ul className="space-y-1.5">
                    {group.keys.map(([key, label]) => (
                      <li key={key} className="flex items-center gap-2 text-sm">
                        <kbd className="min-w-9 shrink-0 rounded border bg-muted px-1.5 py-0.5 text-center font-mono text-[11px]">
                          {key}
                        </kbd>
                        <span className="text-muted-foreground">{label}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              ))}
            </div>
          </section>

          <p className="border-t pt-4 text-sm text-muted-foreground">
            Something wrong or missing?{" "}
            <Link href="/team" className="underline underline-offset-2 hover:text-foreground">
              Ask whoever runs your pilot
            </Link>
            .
          </p>
        </div>
      </div>
    </PageShell>
  );
}
